shivansh-bhatnagar18/multiplayer-uno

INSTALLATION.md
Updated the frontend port from `3000` to the default Vite port `5173`, and modified the frontend start command from `npm start` to `npm run dev`.
Fixes #7
=> doc: Update frontend development server port to 5173

backend/uno-game-engine/engine.js
This adds a check to ensure there are enough cards in the deck to allot to all players. And then distributes the cards to all players from the shuffled deck.
Fixes #3
<details>
<summary>Screenshots and screen captures</summary>
</details>
<details>
<summary>Self-review checklist</summary>
Completed manual review and testing of the following:
- [NA] Visual appearance of the changes.
- [NA] End-to-end functionality of buttons, interactions and flows.
</details>
=> engine: Implement Card Allotment Logic

backend/gameStore.js, backend/gameStore.ts, backend/package.json, backend/uno-game-engine/deck.ts
Implemented the createGame function which creates a new game, generates it's id and adds it the the games map.
Also added the retrieveGame function which retrieves a game, given it's id.
Also added the uuid package to generate unique ids for games.
Fixes #5
<details>
<summary>Screenshots and screen captures</summary>
</details>
<details>
<summary>Self-review checklist</summary>
Completed manual review and testing of the following:
</details>
=> gameStore: Added functions to add and retrieve games

backend/src/types.d.ts, backend/uno-game-engine/engine.ts
This commit converts the engine to typescript, and adds relevant types for all relevant functions and variables.
The player type is set to have a id field, and cards field containing
an array of UNOCards
Fixes #25
The test fails due to eslint disallowing any type
=> engine: Convert to typescript

backend/src/types.d.ts, backend/uno-game-engine/deck.ts
- Created an ID in the format `card-type-color-value`.
- Added a `sameCardCount` array to uniquely identify cards of the same type and color.
- Generated a unique ID using the format `card-type-color-value-sameCardCount[id]`.
Fixes #4 
<h3>Reason for choosing custom unique id instead of UUID etc</h3>
1. Custom unique id contains meaningful information about the card that may help in future debuging. For example: `card-Special-Red-skip-2` immediately conveys that the card is a red "skip" card and it is the second one of its kind.
2. Generating custom id is computationally cheaper and simpler compared to generating a UUID.
3. IDs like `card-Special-Red-skip-2` are `human-readable`, making it easier for developers and testers to trace issues, verify game logic, and understand game states …
=> deck: Assigned unique id to each card.

backend/tests/deck.test.ts, backend/uno-game-engine/deck.ts
Fixes: #2
Shuffled the deck using Fiesher-Yates algorithm
=> deck: Implemented Fisher-Yates shuffling algorithm to shuffle the deck

backend/src/types.d.ts, backend/tests/deck.test.ts, backend/uno-game-engine/deck.ts
1. Added black to CardColor in types.d.ts.
2. Split special and wild cards into specialValues and wildCardValues arrays.
3. For each color in the colors array:
- Add two cards for each number (0-9), except one card for '0'.
- Add two cards for each special value.
- For 'black', add four cards for each wild card value.
Fixes: #1
=> deck: completed function to create and shuffle a UNO card deck.

backend/tests/engine.test.ts, backend/uno-game-engine/engine.ts
Fixes: #8 
Handles the card drawing logic from an empty cardDeck.
- Reshuffles the thrown cards into the card deck when the card deck is empty and a player needs to draw a card.
- Return Succes or Error based on the outcome.
- Also added relevant unit test, in engine.test.ts, to verify this `drawCardFromDeck()` works correctly.
I have created a sample test in engine.test.ts.
just run `npm test`
=> engine: improved card drawing logic.

frontend/src/library/toast/Toast.tsx, frontend/src/library/toast/toast-context.ts, frontend/src/library/toast/toast.css, frontend/src/main.tsx
This commit creates the toast component with customizable position,duration and color.
fixes:#68
Created the toast component with customizable position,duration and color.To use you need use the custom hook useToast() 
and then toast.open(message,duration,position,color) to get the toast at that desired position.
[Explain the motivation behind these changes and provide any relevant context.]
[Describe the steps to test the changes made in this pull request.]
[If applicable, mention any related issues or pull requests.]
https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/72665321/bee1228f-d607-4b68-b6ee-cc3fafcac1ba
=> Designed a Toast Component

frontend/src/library/heading.tsx, frontend/src/pages/PlayOptions.tsx
I have created a highly customizable and reusable header component in src/library, and the styling is done using tailwind css and added various input fields as props.
I have also modified and updated my previously created playoptions page(which is merged) with this heading component. This heading component has various props which you can see in attached screenshot.
Fixes: #67 
- Run 'npm run dev' under frontend directory
- Navigate to /play and you can see use of customizable header component
- #67
=> Frontend: Added a customizable  and reusable heading component

frontend/src/index.css, frontend/src/library/button.tsx, frontend/src/pages/PlayOptions.tsx, frontend/tailwind.config.js
I have created a customizable and reusable button based on the given figma design, in src/library.
I have used all possible input props and styled using tailwind css and added some custom pluggins and css as required.
Fixes: #76
- #76
=> Frontend: designed a custom button component based on figma design

backend/src/eventRecipients.ts
Created two functions that pushes the event object into the event queue of a specific client id.
The second Function sends the each event of the given client id to all the eligible client id (i.e only if response object is available).
[Explain the motivation behind these changes and provide any relevant context.]
[Describe the steps to test the changes made in this pull request.]
[If applicable, mention any related issues or pull requests.]
=> client:Implemented the enqueuing mechanism for clients

frontend/src/library/input.module.css, frontend/src/library/input.tsx, frontend/tailwind.config.js
fixes:#77
Created the Input component as discussed and made in figma. As props it takes normal input properties like placeholder,value etc. The styling has been done in input.css (I had to rename it input.css from input.module.css as it was not working when importing)
[Explain the motivation behind these changes and provide any relevant context.]
[Describe the steps to test the changes made in this pull request.]
[If applicable, mention any related issues or pull requests.]
=> Client:Implemented the input component

frontend/src/Navbar.tsx, frontend/src/pages/Error.tsx
I have used useNavigate hook in place of window.
location.href for better web performance,
wherever required
fixes: #89
- run "npm run dev"
- navigate different pages
- #89
=> Frontend: implemented useNavigate hook at required loactions

ARCHITECTURE.md, backend/src/uno-game-engine/engine.ts, backend/src/uno-game-engine/events/throwCard.ts, backend/tests/engine.test.ts
adds the throw card handler
Fixes #44 
[Explain the motivation behind these changes and provide any relevant context.]
[Describe the steps to test the changes made in this pull request.]
[If applicable, mention any related issues or pull requests.]
=> gameEvent: Implement Throw Card Event

backend/src/types.d.ts, backend/src/uno-game-engine/engine.ts, backend/src/uno-game-engine/events/leaveGame.ts
Created the LEAVE_GAME event handler which removes the player from the current game then takes the card that the player has then puts it in the deck and shuffles the deck for the current players to continue their game.
=> server:Add game event handler for LEAVE_GAME event

backend/src/uno-game-engine/events/joinGame.ts
Created the event handler for JOIN_GAME event to let new players join the server before the game is started by the host.
=> server:Add game event handler for JOIN_GAME event

frontend/src/App.tsx, frontend/src/Navbar.tsx, frontend/src/contexts/AuthContext.tsx, frontend/src/library/button.tsx, frontend/src/library/input.tsx, frontend/src/pages/Home.tsx, frontend/src/pages/Login.tsx, frontend/src/pages/SignUp.tsx
Added Login Page & Signup Page with other modifications
Fixes: #79
Added a login page with changes to some components namely:
1)Button component was changed to include `type` as a prop.
2)Input button was changed to adjust the roundness and the height and width props were made editable .
3)NavBar was modified to conditionally render the signin/login button.
4)Routes for Login and Signup pages were added.
5)Implemented authContext to the login page
- run the command `npm run dev`
- access the /login route
#80 
#87 
#76
=> Frontend: Added Login Page with modifications to other components

frontend/index.html, frontend/src/Navbar.tsx, frontend/src/library/aboutUsModal.tsx, frontend/src/pages/Home.tsx
Added About Us modal
Fixes : #100
Added The About Us modal . Reused the structure used in rules modal
=> Added About Us

frontend/index.html
Changed the title and logo of the website to the project name and logo which is available in the public folder.
=> client:Change the title and the logo

backend/src/types.ts, frontend/package-lock.json, frontend/package.json, frontend/src/library/chatbox/Chatbox.tsx, frontend/src/library/chatbox/Message.tsx, frontend/src/library/chatbox/MessageInput.tsx, frontend/src/library/chatbox/MessageList.tsx, frontend/src/pages/Game.tsx
Added a collapsible chat box in the gamepage, which contains messagelist, input box, reactions to messages. The necessary files are added in a folder Chatbox in src/library. The folder include files namely
1.types.ts
2.chatbox.tsx
3.Message.tsx
4.MessageInput.tsx
5.MessageList.tsx
The packages emoji picker react and react icons are also installed.
fixes #125
- Run "npm run dev" in frontend directory
- navigate to /game
- Click on chat icon at bottom
- #125
=> Frontend: Added a chat box in the game page

backend/src/types.ts, backend/src/uno-game-engine/engine.ts, backend/src/uno-game-engine/events/announceUno.ts, backend/src/uno-game-engine/events/drawCard.ts, backend/src/uno-game-engine/events/eventHandlerUtils.ts, backend/src/uno-game-engine/events/joinGame.ts, backend/src/uno-game-engine/events/throwCard.ts, backend/src/uno-game-engine/gameEvents.ts, backend/tests/engine.test.ts, backend/tests/events.test.ts, frontend/src/channel.ts
Fixes: #132
In short:
- Created `announced_uno` event.
- Added `runningEvents` with `vulnerableToUNO` and `hasAnnouncedUNO` subfields in engine.ts.
- Created `getThrowableCards()` in eventHandlerUtils.
- Handled corner cases related to the announced_uno event.
- Created tests for the announced_uno event and its corner cases.
The plan this PR followed to handle `ANNOUNCE_UNO` event:
- Players can announce UNO only if:
- It's their turn and they have 2 cards, with at least one throwable card.
- OR before the other players catch him not saying UNO.
- If a player fails to say "UNO" and isn't caught before the next player plays, they are considered to have announced UNO.
- Added `runningEvents` field in GameEngine with sub-fields `vulnerableToUNO` and `hasAnnouncedUNO`.
- Checked if the new …
=> gameEvents: created `ANNOUNCE_UNO` event

backend/src/types.ts, backend/src/uno-game-engine/events/challengeUno.ts, backend/src/uno-game-engine/gameEvents.ts, backend/tests/events.test.ts
fixes: #145
- Created `challengeUno.ts`.
- Checked if a player can be challenged.
- Player can be challenged only if `vulnerableToUNO` is equal to that player.
- If the challenge is successful, the player must draw two cards from the deck as a penalty.
- Created tests for the challenge_uno event and its corner cases in `events.test.ts`.
I have created some tests in `events.test.ts`
=> gameEvents: created `CHALLENGE_UNO` event.

frontend/src/pages/Game.tsx
The game properties button is added at bottom left of the gamepage, on clicking. we can anytime open and display the GamePropertiesModal within the game.
Also added a Leave game button in GamePropertiesModal which triggers the LEAVE_GAME event using channel.triggerEvent and navigates to homepage.
Both changes done in seperate commits.
fixes #161 
- Navigate to gamePage
- #161 
[Screencast from 2024-06-25 16-48-38.webm](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/153260291/26c032a5-1c50-4ae9-b97f-4e612d969918)
=> GamePage: Added the Game properties button and leave game button in modal

frontend/src/clientDispatch.ts, frontend/src/pages/Game.tsx
Making the uno button functioning
Set uno button to trigger Announce_Uno Event and  added a handler for this event" -m 
Fixes : #159 
=> Make the UNO button functioning 

frontend/src/pages/Game.tsx
1. Brightened player icons for active turn indication.
2. Displayed current player's name on game board.
4. Tailwind CSS utility classes have been applied for consistent styling of the player's name.
=> Frontend: Display The Player Whose Turn It Is Currently

backend/src/controllers/eventControllers.ts, frontend/src/clientDispatch.ts, frontend/src/pages/Game.tsx
Added handler for StartGame at frontend and made some minor corrections. Also Triggered Sync_State Event after Start_Game and draw_card event as these events make changes using backend functions.
These changes require to synced just after the event is triggered
=> Fixed the functionality of START_GAME Event

frontend/src/library/Player.tsx, frontend/src/pages/Game.tsx
Fixes #158
1. The Player component was refactored to separate JSX for rendering player cards.
2. Highlighting functionality was added to indicate the current player's turn.
3. Player names were styled to appear in a white box with black text.
4. Brightness adjustment was applied to highlight the active player.
=> Frontend: Display Player names along with cards

frontend/src/Navbar.tsx, frontend/src/library/modal/ModalContext.tsx, frontend/src/pages/Game.tsx, frontend/src/pages/Home.tsx
Updated the modal system which allows the content that changes often to render dynamically. In this change you have to pass an id to the modal and if the modal with that id is opened then it will update the content inside the modal dynamically.
`cd frontend`
`npm run dev`
- #168
=>  Client: Make the modal system more compatible with dynamic content

frontend/src/pages/Login.tsx
1. If the user is not logged in, they are redirected to the login page.
2. After successful login, the user is directly navigated to the game they intended to join instead of the home page.
Fixes: #174 
1. Attempt to join a game using a code or link while not logged in.
2. Verify redirection to the login page.
3. Log in with valid credentials.
4. Confirm that you are navigated directly to the game instead of the home page.
https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/59174836/bc566b57-e7c4-4080-a9ec-a7ad51d91b7a
=> join: Navigate to game upon login during game join.

frontend/src/Navbar.tsx, frontend/src/index.css, frontend/src/library/modal/Modal.tsx, frontend/src/library/modal/ModalContext.tsx
Added tailwind transition and transform properties with state change of sidebar and modal, giving fading effect on opening and closing.
fixes #131
- Run "npm run dev"
- #131 
[Screencast from 2024-06-30 10-46-17.webm](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/153260291/1f1ff952-97a1-4568-b5b7-91ecf523c97d)
=> Frontend: Implemented fading in & out effect on opening and closing of sidebar and modal objects
